cargo-features = ["trim-paths", "panic-immediate-abort"]

[package]
name = "hider"
version = "0.1.0"
edition = "2024"

[dependencies]
crc32fast = "1.5.2"
reed-solomon-erasure = "6.0.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
zstd = "0.14.0"

[dev-dependencies]
tempfile = "3.27.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "immediate-abort"
strip = true
trim-paths = "all"
overflow-checks = false
